#!/bin/bash

case $1 in

	db:start)
		cd docker && docker-compose up -d
		cd ..
		echo "DB started"
		;;

	db:refresh)
		echo "about to rewrite db";
		dropdb --host=127.0.0.1 --port=5432 -e -U postgres postgres;
		createdb --host=127.0.0.1 --port=5432 -e -U postgres -O postgres postgres;
		;;

	db:rewrite)
		echo "about to rewrite db";
		dropdb --host=127.0.0.1 --port=5432 -e -U postgres postgres;
		createdb --host=127.0.0.1 --port=5432 -e -U postgres -O postgres postgres;
		cat sql/inout/*.sql | psql --host=127.0.0.1 --port=5432 -U postgres -d postgres -a -1
		;;

	db:rewrite:mutations)
		psql --host=127.0.0.1 --port=5432 -U postgres -d postgres -a -1 -f sql/inout/5_mutations.sql
		;;	
	db:rewrite:querys)
		psql --host=127.0.0.1 --port=5432 -U postgres -d postgres -a -1 -f sql/inout/6_querys.sql
		;;	
	db:seed)
		echo "seeding database"
		psql --host=127.0.0.1 --port=5432 -U postgres -d postgres -a -1 -f sql/data.sql
		;;
	db:repair)
		echo "repairing sequence"
		psql --host=127.0.0.1 --port=5432 -U postgres -d postgres -a -1 -f sql/repair_seq.sql
		;;

	db:interactive)
		psql --host=127.0.0.1 --port=5432 -U postgres -d postgres
		;;

	redis:seed)
		node main/seedRedis.js
		;;
	*)
		echo "unknown"
		;;
esac
